spring:
  security:
    jwt:
      key: abcdefg
      expiry: 7

  datasource:
    url: jdbc:mysql://localhost:3306/myschool
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

