spring:
  security:
    jwt:
      key: abcdefg
      expiry: 7

  mail:
    password: DMgXk5Q9NZEyyPkd
    host: smtp.163.com
    username: wanzx11@163.com

  rabbitmq:
    stream:
      username: root
      password: 123456o
      host: localhost
      port: 5672

  datasource:
    url: jdbc:mysql://localhost:3306/myschool
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

